### ISSUE TITLE
PCSX2 refuse to build

### ISSUE THREAD

**Issue by Nevrdid** [V0rt3x667/ArchyPie-Setup#50]
Hi, i am currently trying to add pcsx2 but it first failed because the patch would not apply so i fixed it looking at pcsx2 source but even with this, the emulator won't build around while building pcsx2-qt.
I was wondering, why don't you just use yay to build things and just move things around after aur managed well things ? x)
Thanks for your work anyway.
Succesfully enabled it installing pcsx2-git and copying /opt/pcsx2 to tmp/build/pcsx2/build/bin while installing it from source. ^^'

**Comment by V0rt3x667** [comment]
Hi, thanks for reporting the issue, I will look into it. The reason I don't use AUR is because I would be dependent on the person who maintains the pkg build file to keep it up to date and I won't have any input on making changes if required. I used to maintain my own packages under a different project called Arch-RGS but it just became too much work looking after both pkgbuild files and bash scripts.

**Comment by V0rt3x667** [comment]
Hi, I have added commit 90bfae2 which addresses all the issues. If you want to test it please update the script via the setup menu. Thanks

**Comment by V0rt3x667** [comment]
Closing as fixed.
